# Generated by Django 3.2.11 on 2022-11-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_finished',
            field=models.DateField(auto_now_add=True),
        ),
    ]
